services:
  restaurant-service:
    build:
      context: .
      dockerfile: restaurant-service/Dockerfile
    container_name: lab8-restaurant-service
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - RABBITMQ_HOST=213.199.42.57
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=students
      - RABBITMQ_PASS=Ut3c2026
      - RABBITMQ_VHOST=/
    volumes:
      - ./restaurant-service:/app
      - ./shared:/app/shared

  rewards-service:
    build:
      context: .
      dockerfile: rewards-service/Dockerfile
    container_name: lab8-rewards-service
    environment:
      - RABBITMQ_HOST=213.199.42.57
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=students
      - RABBITMQ_PASS=Ut3c2026
      - RABBITMQ_VHOST=/
    volumes:
      - ./rewards-service:/app
      - ./shared:/app/shared

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: lab8-notification-service
    environment:
      - RABBITMQ_HOST=213.199.42.57
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=students
      - RABBITMQ_PASS=Ut3c2026
      - RABBITMQ_VHOST=/
    volumes:
      - ./notification-service:/app
      - ./shared:/app/shared
